sources:
  - name: Hashavshevet
    handler:
      jsonSchema:
        baseUrl: 'https://{env.HASHAVSHEVET_MESH_URL}/'
        # baseSchema: ./json-schemas/hashavshevetSchema.json
        operationHeaders:
          Authorization: 'Bearer {env.HASHAVSHEVET_MESH_AUTH_TOKEN}'
          host: '{env.HASHAVSHEVET_MESH_URL}'
          Content-Type: application/x-www-form-urlencoded
          Accept: application/json
        operations:
          - type: Query
            field: getSession
            path: /api/napi
            method: POST
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getSessionResopnse
          - type: Query
            field: getCompanies
            path: /CompanyListToTokenApi/TokenCompanies
            method: POST
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getCompaniesResopnse

          - type: Query
            field: getRecords
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getRecordsRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getRecordsResponse

          - type: Query
            field: getTransactions
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getTransactionsRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getTransactionsResponse
          - type: Mutation
            field: importTransactionsToBatch
            path: /jtransApi/tmpBatch
            method: POST
            requestSchema: ./json-schemas/importTransactionsToBatchRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/importTransactionsToBatchResponse

          - type: Mutation
            field: createBatch
            path: /jtransApi/newBatch
            method: POST
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/createBatch
          - type: Query
            field: getBatch
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getBatchRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getBatchResponse
          - type: Query
            field: checkBatch
            path: /jtransApi/chkBatch
            method: POST
            requestSchema: ./json-schemas/checkBatchRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/checkBatchResponse
          - type: Mutation
            field: issueBatch
            path: /jtransApi/issueBatch
            method: POST
            requestSchema: ./json-schemas/issueBatchRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/issueBatchResponse

          - type: Query
            field: getAccounts
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getAccountsRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getAccountsResponse
          # importAccounts (importIndexRecords)
          # importItems (importIndexRecords)
          # deleteIndexRecords

          - type: Query
            field: getBankPageRecords
            path: /ExportDataApi/exportData
            method: POST
            requestSchema: ./json-schemas/getBankPageRecordsRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/getBankPageRecordsResponse
          - type: Mutation
            field: importBankPage
            path: /BankPagesApi/importBankPage
            method: POST
            requestSchema: ./json-schemas/importBankPageRequest.json
            responseSchema: ./json-schemas/hashavshevetSchema.json#/definitions/importBankPageResponse

            # createDocument
            # showDocument
            # delDocument
            # issueDoc

            # crmActivities
            # crmActivitiesTest

    transforms:
      - resolversComposition:
          mode: bare
          compositions:
            - resolver: Query.getRecords
              composer: ./src/resolvers/mesh-resolvers#getRecordsResolver
            - resolver: Query.getTransactions
              composer: ./src/resolvers/mesh-resolvers#getTransactionsResolver
            - resolver: Query.getBatch
              composer: ./src/resolvers/mesh-resolvers#getBatchResolver
            - resolver: Query.getAccounts
              composer: ./src/resolvers/mesh-resolvers#getAccountsResolver
            - resolver: Query.getBankPageRecords
              composer: ./src/resolvers/mesh-resolvers#getBankPageRecordsResolver
serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2

require:
  - ts-node/register/transpile-only

additionalTypeDefs: |
  extend type HashavshevetSchemaJsonTransaction {
    batch: HashavshevetSchemaJsonBatch
    records: [HashavshevetSchemaJsonRecord]
    creditor: HashavshevetSchemaJsonAccount
    debtor: HashavshevetSchemaJsonAccount
  }
  extend type HashavshevetSchemaJsonBatch {
    transactions: [HashavshevetSchemaJsonTransaction]
  }
  extend type HashavshevetSchemaJsonRecord {
    transaction: HashavshevetSchemaJsonTransaction
    batch: HashavshevetSchemaJsonBatch
    account: HashavshevetSchemaJsonAccount
    counterAccount: HashavshevetSchemaJsonAccount
  }
  extend type HashavshevetSchemaJsonBankPageRecord {
    account: HashavshevetSchemaJsonAccount
  }
  extend type importTransactionsToBatchResponse {
    batch: HashavshevetSchemaJsonBatch
  }

additionalResolvers:
  - ./src/resolvers/mesh-resolvers
